### ISSUE TITLE
server_status bombs if no jobs have been pushed yet

### ISSUE THREAD

**Issue by icook** [simplecrypto/powerpool#111]
```
 scheduler stdout | 2014-12-01 19:59:15,041 [simplecoin] [ERROR]: Unhandled exception in server_status
 scheduler stdout | Traceback (most recent call last):
 scheduler stdout |   File "/storage/simplecoin_multi/simplecoin/scheduler.py", line 51, in crontab
 scheduler stdout |     res = func(*args, **kwargs)
 scheduler stdout |   File "/storage/simplecoin_multi/simplecoin/scheduler.py", line 1279, in server_status
 scheduler stdout |     if 'last_flush_job' in data and 'currency' in data['last_flush_job']:
 scheduler stdout | TypeError: argument of type 'NoneType' is not iterable
 scheduler stdout | 2014-12-01 19:59:15,043 [apscheduler.scheduler] [INFO]: Job "server_status (trigger: cron[second='15'], next run at: 2014-12-01 20:00:15)" executed successfully
```

**Comment by ericecook** [comment]
Lol this is a SCM bug. Fixed fc904f37f8c91570d069a85cf7485e3ff91ee372
