### ISSUE TITLE
EarthCoin Does not work

### ISSUE THREAD

**Issue by crackfoo** [simplecrypto/powerpool#122]
2015-02-13 06:31:16,685 [MonitorNetwork_EarthCoin] [ERROR] Block failed to submit to the server 127.0.0.1:5121!
Traceback (most recent call last):
  File "/home/crackers/www/pools/simple/simplecode/powerpool/powerpool/jobmanagers/monitor_network.py", line 180, in submit_block
    res = conn.submitblock(block)
  File "/home/crackers/www/pools/simple/simplecode/cryptokit1/cryptokit/rpc.py", line 194, in __call__
    return self._get_response(response)
  File "/home/crackers/www/pools/simple/simplecode/cryptokit1/cryptokit/rpc.py", line 222, in _get_response
    raise CoinRPCException(response['error'])
CoinRPCException: Block decode failed
2015-02-13 06:31:16,685 [MonitorNetwork_EarthCoin] [ERROR] {u'message': u'Block decode failed', u'code': -22}
2015-02-13 06:31:16,688 [MonitorNetworkMulti_SWITCH-SHA256] [WARNING] Unable to grab profit info for FFC!
2015-02-13 06:31:16,689 [MonitorNetwork_EarthCoin] [ERROR] Block failed to submit to the server 127.0.0.1:5121!
Traceback (most recent call last):
  File "/home/crackers/www/pools/simple/simplecode/powerpool/powerpool/jobmanagers/monitor_network.py", line 190, in submit_block
    res = conn.getblocktemplate(block)
  File "/home/crackers/www/pools/simple/simplecode/cryptokit1/cryptokit/rpc.py", line 194, in __call__
    return self._get_response(response)
  File "/home/crackers/www/pools/simple/simplecode/cryptokit1/cryptokit/rpc.py", line 222, in _get_response
    raise CoinRPCException(response['error'])
CoinRPCException: value is type str, expected obj
2015-02-13 06:31:16,689 [MonitorNetwork_EarthCoin] [ERROR] {u'message': u'Invalid mode', u'code': -8}
2015-02-13 06:31:16,689 [MonitorNetwork_EarthCoin] [ERROR] Block failed to submit to the server 127.0.0.1:5121, server returned failed!
Traceback (most recent call last):
  File "/home/crackers/www/pools/simple/simplecode/powerpool/powerpool/jobmanagers/monitor_network.py", line 190, in submit_block
    res = conn.getblocktemplate(block)
  File "/home/crackers/www/pools/simple/simplecode/cryptokit1/cryptokit/rpc.py", line 194, in __call__
    return self._get_response(response)
  File "/home/crackers/www/pools/simple/simplecode/cryptokit1/cryptokit/rpc.py", line 222, in _get_response
    raise CoinRPCException(response['error'])
CoinRPCException: value is type str, expected obj
2015-02-13 06:31:16,893 [StratumServer_SHA256_STRAT] [INFO] VARDIFF: Moving to D128 from D256 on XtMVSeB6S89A7SBP4T2mz1nNpU732C6mfS.blizzen
2015-02-13 06:31:16,893 [StratumServer_SHA256_STRAT] [INFO] Pushing diff update 256 -> 128 before job for XtMVSeB6S89A7SBP4T2mz1nNpU732C6mfS.blizzen
2015-02-13 06:31:17,690 [MonitorNetwork_EarthCoin] [INFO] Retry 1 for connection 127.0.0.1:5121
2015-02-13 06:31:17,692 [MonitorNetwork_EarthCoin] [ERROR] Block failed to submit to the server 127.0.0.1:5121!
Traceback (most recent call last):
  File "/home/crackers/www/pools/simple/simplecode/powerpool/powerpool/jobmanagers/monitor_network.py", line 180, in submit_block
    res = conn.submitblock(block)
  File "/home/crackers/www/pools/simple/simplecode/cryptokit1/cryptokit/rpc.py", line 194, in __call__
    return self._get_response(response)
  File "/home/crackers/www/pools/simple/simplecode/cryptokit1/cryptokit/rpc.py", line 222, in _get_response
    raise CoinRPCException(response['error'])
CoinRPCException: Block decode failed
2015-02-13 06:31:17,692 [MonitorNetwork_EarthCoin] [ERROR] {u'message': u'Block decode failed', u'code': -22}
2015-02-13 06:31:17,695 [MonitorNetwork_EarthCoin] [ERROR] Block failed to submit to the server 127.0.0.1:5121!
Traceback (most recent call last):
  File "/home/crackers/www/pools/simple/simplecode/powerpool/powerpool/jobmanagers/monitor_network.py", line 190, in submit_block
    res = conn.getblocktemplate(block)
  File "/home/crackers/www/pools/simple/simplecode/cryptokit1/cryptokit/rpc.py", line 194, in __call__
    return self._get_response(response)
  File "/home/crackers/www/pools/simple/simplecode/cryptokit1/cryptokit/rpc.py", line 222, in _get_response
    raise CoinRPCException(response['error'])
CoinRPCException: value is type str, expected obj
2015-02-13 06:31:17,695 [MonitorNetwork_EarthCoin] [ERROR] {u'message': u'Invalid mode', u'code': -8}
2015-02-13 06:31:17,695 [MonitorNetwork_EarthCoin] [ERROR] Block failed to submit to the server 127.0.0.1:5121, server returned failed!
Traceback (most recent call last):
  File "/home/crackers/www/pools/simple/simplecode/powerpool/powerpool/jobmanagers/monitor_network.py", line 190, in submit_block
    res = conn.getblocktemplate(block)
  File "/home/crackers/www/pools/simple/simplecode/cryptokit1/cryptokit/rpc.py", line 194, in __call__
    return self._get_response(response)
  File "/home/crackers/www/pools/simple/simplecode/cryptokit1/cryptokit/rpc.py", line 222, in _get_response
    raise CoinRPCException(response['error'])
CoinRPCException: value is type str, expected obj
2015-02-13 06:31:18,695 [MonitorNetwork_EarthCoin] [INFO] Retry 2 for connection 127.0.0.1:5121
2015-02-13 06:31:18,697 [MonitorNetwork_EarthCoin] [ERROR] Block failed to submit to the server 127.0.0.1:5121!
Traceback (most recent call last):
  File "/home/crackers/www/pools/simple/simplecode/powerpool/powerpool/jobmanagers/monitor_network.py", line 180, in submit_block
    res = conn.submitblock(block)
  File "/home/crackers/www/pools/simple/simplecode/cryptokit1/cryptokit/rpc.py", line 194, in __call__
    return self._get_response(response)
  File "/home/crackers/www/pools/simple/simplecode/cryptokit1/cryptokit/rpc.py", line 222, in _get_response
    raise CoinRPCException(response['error'])
CoinRPCException: Block decode failed
2015-02-13 06:31:18,697 [MonitorNetwork_EarthCoin] [ERROR] {u'message': u'Block decode failed', u'code': -22}
2015-02-13 06:31:18,700 [MonitorNetwork_EarthCoin] [ERROR] Block failed to submit to the server 127.0.0.1:5121!
Traceback (most recent call last):
  File "/home/crackers/www/pools/simple/simplecode/powerpool/powerpool/jobmanagers/monitor_network.py", line 190, in submit_block
    res = conn.getblocktemplate(block)
  File "/home/crackers/www/pools/simple/simplecode/cryptokit1/cryptokit/rpc.py", line 194, in __call__
    return self._get_response(response)
  File "/home/crackers/www/pools/simple/simplecode/cryptokit1/cryptokit/rpc.py", line 222, in _get_response
    raise CoinRPCException(response['error'])
CoinRPCException: value is type str, expected obj
2015-02-13 06:31:18,700 [MonitorNetwork_EarthCoin] [ERROR] {u'message': u'Invalid mode', u'code': -8}
2015-02-13 06:31:18,700 [MonitorNetwork_EarthCoin] [ERROR] Block failed to submit to the server 127.0.0.1:5121, server returned failed!
Traceback (most recent call last):
  File "/home/crackers/www/pools/simple/simplecode/powerpool/powerpool/jobmanagers/monitor_network.py", line 190, in submit_block
    res = conn.getblocktemplate(block)
  File "/home/crackers/www/pools/simple/simplecode/cryptokit1/cryptokit/rpc.py", line 194, in __call__
    return self._get_response(response)
  File "/home/crackers/www/pools/simple/simplecode/cryptokit1/cryptokit/rpc.py", line 222, in _get_response
    raise CoinRPCException(response['error'])
CoinRPCException: value is type str, expected obj

**Comment by ericecook** [comment]
EarthCoin requires TX messages (https://bitcointalk.org/index.php?topic=379236.0). TX messages are not currently supported
