### ISSUE TITLE
TypeError: coinbase() got an unexpected keyword argument 'desc_string'

### ISSUE THREAD

**Issue by frndxyz** [simplecrypto/powerpool#135]
receiving this error when pool getting blocktemplate...

**Comment by icook** [comment]
Please provide log output and config.

**Comment by frndxyz** [comment]
thanks @icook , but when i removed "desc_string" params everything works fine..

**Comment by granatgas** [comment]
hi icook,
can you help me?
i have same problem

Traceback (most recent call last):
  File "/home/gas/Envs/powerpool/local/lib/python2.7/site-packages/gevent/event.py", line 114, in _notify_links
    link(self)
  File "/home/gas/powerpool/powerpool/jobmanagers/monitor_network.py", line 303, in new_merged_work
    self.generate_job(push=True, flush=event.flush, network='aux')
  File "/home/gas/powerpool/powerpool/jobmanagers/monitor_network.py", line 363, in generate_job
    desc_string=self.config['coinbase_string']))
TypeError: coinbase() got an unexpected keyword argument 'desc_string'
(<bound method MonitorNetwork.new_merged_work of <powerpool.jobmanagers.monitor_network.MonitorNetwork object at 0x7f7219b91790>>,
 <gevent.event.Event object at 0x7f7219b919d0>) failed with TypeError

Traceback (most recent call last):
  File "/home/gas/Envs/powerpool/local/lib/python2.7/site-packages/gevent/event.py", line 114, in _notify_links
    link(self)
  File "/home/gas/powerpool/powerpool/jobmanagers/monitor_network.py", line 303, in new_merged_work
    self.generate_job(push=True, flush=event.flush, network='aux')
  File "/home/gas/powerpool/powerpool/jobmanagers/monitor_network.py", line 363, in generate_job
    desc_string=self.config['coinbase_string']))
TypeError: coinbase() got an unexpected keyword argument 'desc_string'
(<bound method MonitorNetwork.new_merged_work of <powerpool.jobmanagers.monitor_network.MonitorNetwork object at 0x7f7219b917d0>>,
 <gevent.event.Event object at 0x7f7219b919d0>) failed with TypeError

2015-11-01 14:19:22,602 [MonitorNetworkMulti_SWITCH] [WARNING] Unable to grab profit info for DNOTE!
2015-11-01 14:19:22,608 [MonitorNetwork_BTCS] [ERROR] Unhandled error in _check_new_jobs
Traceback (most recent call last):
  File "/home/gas/powerpool/powerpool/lib.py", line 97, in wrapper
    res = f(self, *args, **kwargs)
  File "/home/gas/powerpool/powerpool/jobmanagers/monitor_network.py", line 260, in _check_new_jobs
    self.getblocktemplate()
  File "/home/gas/powerpool/powerpool/jobmanagers/monitor_network.py", line 300, in getblocktemplate
    self.generate_job(push=new_block, flush=new_block, new_block=new_block)
  File "/home/gas/powerpool/powerpool/jobmanagers/monitor_network.py", line 363, in generate_job
    desc_string=self.config['coinbase_string']))
TypeError: coinbase() got an unexpected keyword argument 'desc_string'
2015-11-01 14:19:22,617 [MonitorNetwork_BTCS] [ERROR] Unhandled error in _poll_height
Traceback (most recent call last):
  File "/home/gas/powerpool/powerpool/lib.py", line 97, in wrapper
    res = f(self, *args, **kwargs)
  File "/home/gas/powerpool/powerpool/jobmanagers/monitor_network.py", line 256, in _poll_height
    self.getblocktemplate(new_block=True)
  File "/home/gas/powerpool/powerpool/jobmanagers/monitor_network.py", line 300, in getblocktemplate
    self.generate_job(push=new_block, flush=new_block, new_block=new_block)
  File "/home/gas/powerpool/powerpool/jobmanagers/monitor_network.py", line 363, in generate_job
    desc_string=self.config['coinbase_string']))
TypeError: coinbase() got an unexpected keyword argument 'desc_string'
2015-11-01 14:19:22,626 [MonitorNetwork_DNOTE] [ERROR] Unhandled error in _poll_height
Traceback (most recent call last):
  File "/home/gas/powerpool/powerpool/lib.py", line 97, in wrapper
    res = f(self, *args, **kwargs)
  File "/home/gas/powerpool/powerpool/jobmanagers/monitor_network.py", line 256, in _poll_height
    self.getblocktemplate(new_block=True)
  File "/home/gas/powerpool/powerpool/jobmanagers/monitor_network.py", line 300, in getblocktemplate
    self.generate_job(push=new_block, flush=new_block, new_block=new_block)
  File "/home/gas/powerpool/powerpool/jobmanagers/monitor_network.py", line 363, in generate_job
    desc_string=self.config['coinbase_string']))
TypeError: coinbase() got an unexpected keyword argument 'desc_string'
2015-11-01 14:19:22,629 [MonitorNetwork_DNOTE] [ERROR] Unhandled error in _check_new_jobs
Traceback (most recent call last):
  File "/home/gas/powerpool/powerpool/lib.py", line 97, in wrapper
    res = f(self, *args, **kwargs)
  File "/home/gas/powerpool/powerpool/jobmanagers/monitor_network.py", line 260, in _check_new_jobs
    self.getblocktemplate()
  File "/home/gas/powerpool/powerpool/jobmanagers/monitor_network.py", line 300, in getblocktemplate
    self.generate_job(push=new_block, flush=new_block, new_block=new_block)
  File "/home/gas/powerpool/powerpool/jobmanagers/monitor_network.py", line 363, in generate_job
    desc_string=self.config['coinbase_string']))
TypeError: coinbase() got an unexpected keyword argument 'desc_string'

**Comment by ericecook** [comment]
@granatgas, remove the 'desc_string' attribute from the configuration for that currency.

**Comment by 9cat** [comment]
@ericecook  @frndxyz   when can I move the  'desc_string' attribute. in config.yml? or somewhere else?

I can't find any  'desc_string' attribute. in config.yml.example now.

**Comment by frndxyz** [comment]
@9cat i think from here /home/gas/powerpool/powerpool/jobmanagers/monitor_network.py", line 363, in generate_job
desc_string=self.config['coinbase_string']
