### ISSUE TITLE
Merge mining error for sha256(scrypt works)

### ISSUE THREAD

**Issue by djayr** [simplecrypto/powerpool#143]
Hello mate I was able to merge mine for scrypt algo but having issue to do so with sha256 algorithm.

On startup it doesnt output in console "Now connected to "Main Coin" But it says it's connected to the merged mined coin. 

If I run it in a single mode(mining only main coin) it works but once I add Aux coin into config following error appear on startup:

``` bash
2018-05-27 09:08:19,704 [ServerMonitor_MON] [INFO] Monitoring port listening on ('127.0.0.1', 3886)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "/root/POOL/Powerpool/powerpool/lib.py", line 90, in wrapper
    setup_func()
  File "/root/POOL/Powerpool/powerpool/jobmanagers/base.py", line 75, in _start_monitor_nodes
    .format(serv['username'],
TypeError: string indices must be integers, not str
Sun May 27 09:08:19 2018 <Greenlet at 0x7f2c9b83d190: <bound method MonitorNetwork._monitor_nodes of <powerpool.jobmanagers.monitor_network.MonitorNetwork object at 0x7f2c9c146a10>>> failed with TypeError
```

If I further mine on that port it says

2018-05-27 07:22:28,304 [StratumServer_sha256_STRAT] [WARNING] No jobs available for worker!
2018-05-27 07:22:28,405 [StratumServer_sha256_STRAT] [WARNING] No jobs available for worker!

**Comment by icook** [comment]
I don't have time to dig into this, but it looks like a configuration error. Read `string indices must be integers, not str`, that's likely because a configuration parameter that should be a dictionary is actually a string, likely the connection information since I see `serv['username']`.

Hope that is a push in the right direction.

**Comment by djayr** [comment]
Thank you for reply, The issue was indeed in config file.
