### ISSUE TITLE
Check to ensure correct cleanup is occuring, catch to pretty logs

### ISSUE THREAD

**Issue by icook** [simplecrypto/powerpool#65]
```
2014-08-29 19:27:09,837 [StratumServer] [INFO] Recieving stratum connection from addr ('67.247.216.132', 57371) on sock <socket fileno=136 sock=198.27.67.137:3344>
Traceback (most recent call last):
  File "/home/vertcoin/powerpools/7e3fbed1a15c59a50b7e1700ec46457c5c91e4bf/local/lib/python2.7/site-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/vertcoin/powerpools/powerpool/powerpool/stratum_server.py", line 134, in handle
    client.start()
  File "/home/vertcoin/powerpools/powerpool/powerpool/server.py", line 49, in start
    self.peer_name = self.sock.getpeername()
  File "<string>", line 1, in getpeername
error: [Errno 107] Transport endpoint is not connected
<Greenlet at 0x1991af0: <bound method StratumServer.handle of <StratumServer at 0x141eb90 fileno=6 address=0.0.0.0:3344>>(<socket at 0x198f690 fileno=136 sock=198.27.67.137, ('67.247.216.132', 57371))> failed with error
```

**Comment by ericecook** [comment]
@icook This still an issue?

**Comment by icook** [comment]
Unsure. Grepping prod logs would be easiest to confirm. Likely got fixed when I completely refactored to component arch.
