### ISSUE TITLE
Add PoS support

### ISSUE THREAD

**Issue by ivanech** [simplecrypto/powerpool#80]
When submit block fo PoS coin (I 've tried CryptogenicBullion CGB) got error:

```
2014-09-19 08:48:18,772 [jobmanager] [INFO] Block failed to submit to the server 127.0.0.1:8395 with submitblock! Unable to sign block, wallet locked?
2014-09-19 08:48:18,772 [jobmanager] [ERROR] {u'message': u'Unable to sign block, wallet locked?', u'code': -100}
Traceback (most recent call last):
  File "/home/vital/tmp/powerpool/powerpool/jobmanager.py", line 188, in submit_block
    res = conn.submitblock(block)
  File "/usr/local/lib/python2.7/site-packages/bitcoinrpc/authproxy.py", line 127, in __call__
    raise JSONRPCException(response['error'])
CoinRPCException: Unable to sign block, wallet locked?
```

The signing would be wrong because it is missing the pubkey and instead is using the address.

**Comment by Fcases** [comment]
how about how much would that be worth ?
